# Generated by Django 2.2.1 on 2019-05-16 21:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre de la categoria', max_length=255)),
                ('orden', models.PositiveSmallIntegerField(help_text='estable la prioridad con la que se ordena')),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingrese el titulo de la novedad', max_length=255, unique=True)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('creación', models.DateTimeField(auto_now_add=True)),
                ('modificación', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.Categoria')),
                ('dueño', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'novedades',
            },
        ),
    ]
